#!/bin/bash

# test_05
# It should format css file
# with settings from .editorconfig

TMP_FILE="$(tempfile)"

echo $(cat file) > $TMP_FILE

vim -u vimrc -c "execute 'silent call CSSBeautify()' | w | q | q" $TMP_FILE

RESULT=$(cat $TMP_FILE)

[ "$RESULT" = "$(cat expected)" ]
