#!/bin/bash

# test_09
# It should never use multiple tabs for indentation

TMP_FILE="${TMPDIR:-/tmp/}$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "execute 'silent call JsBeautify()' | w | q | q" "$TMP_FILE"
[ "$(cat $TMP_FILE)" = "$(cat expected)" ]
