" vim -u vimrc
set nocompatible

set nowrap

let root = '~/.vim/bundle'

filetype off
syntax on
set noexpandtab
set tabstop=2
set shiftwidth=2

let g:editorconfig_Beautifier = expand("<sfile>:p:h").'/.editorconfig'

runtime macros/matchit.vim
exec 'set rtp+=../../../'
