#!/bin/bash

TMP_FILE="$(tempfile)"

echo $(cat file) > $TMP_FILE

vim -u vimrc -c "execute 'silent call JsonBeautify()' | w | q | q" $TMP_FILE

RESULT=$(cat $TMP_FILE)

[ "$RESULT" = "$(cat expected)" ]
