#!/bin/bash

# test_02
# It should format css file
# with default settings

TMP_FILE="${TMPDIR:-/tmp/}$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "execute 'silent call CSSBeautify()' | w | q | q" "$TMP_FILE"
[ "$(cat $TMP_FILE)" = "$(cat expected)" ]
