#!/bin/bash

# It should format html file
# with settings from .editorconfig

TMP_FILE="${TMPDIR:-/tmp/}$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "execute 'silent call HtmlBeautify()' | w | q | q" "$TMP_FILE"

RESULT=$(cat $TMP_FILE)
echo "DEBUG -------------------------------"
diff $TMP_FILE expected
echo "END ---------------------------------"

test ! "$(diff $TMP_FILE expected)"
