#!/bin/bash

# issue 25
# Throw error if any section (js, html, css) is empty in global .editorconfig

TMP_FILE="${TMPDIR:-/tmp/}$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "execute 'silent call HtmlBeautify()' | w | q | q" "$TMP_FILE"
[ "$(cat $TMP_FILE)" = "$(cat expected)" ]
