#!/bin/bash

# issue 21
# Tab Indentation does not work
# when we set indent_style = tab in global .editorconfig file

TMP_FILE="$TMPDIR/$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "execute 'silent call JsBeautify()' | w | q | q" "$TMP_FILE"
[ "$(cat $TMP_FILE)" = "$(cat expected)" ]
