#!/bin/bash

# test_01
# It should format javascript file
# with default settings

TMP_FILE="$TMPDIR/$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "execute 'silent call JsBeautify()' | w | q | q" "$TMP_FILE"
[ "$(cat $TMP_FILE)" = "$(cat expected)" ]
