#!/bin/bash

# test_01
# It should format javascript file
# with default settings

TMP_FILE="$(tempfile)"

echo $(cat file) > $TMP_FILE

vim -u vimrc -c "execute 'silent call JsBeautify()' | w | q | q" $TMP_FILE

RESULT=$(cat $TMP_FILE)

[ "$RESULT" = "$(cat expected)" ]
