#!/bin/bash

# test_08
# It should restore position cursor after the beautification

TMP_FILE="$TMPDIR/$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "call setpos('.', [0,1,23,0]) | execute 'silent call JsBeautify()' | call setline('1', getpos('.')) | w | q | q" "$TMP_FILE"
[ "$(cat $TMP_FILE)" = "$(cat expected)" ]
