#!/bin/bash

# issue 18 (https://github.com/maksimr/vim-jsbeautify/issues/18)
# json convert error
# on json from http://help.apple.com/icloud/English.lproj/content.json

TMP_FILE="$(tempfile)"

echo $(cat file) > $TMP_FILE

vim -u vimrc -c "execute 'silent call JsBeautify()' | w | q | q" $TMP_FILE

RESULT=$(cat $TMP_FILE)

[ "$RESULT" = "$(cat expected)" ]
