#!/bin/bash

# test_06
# It should format html file
# with settings from .editorconfig

TMP_FILE='_tmp'

echo $(cat file) > $TMP_FILE

vim -u vimrc -c "execute 'silent call HtmlBeautify()' | w | q | q" $TMP_FILE

RESULT=$(cat $TMP_FILE)

#clean
if [ -f $TMP_FILE ]
then
  rm $TMP_FILE
fi

clear

[ "$RESULT" = "$(cat expected)" ]
