#!/bin/bash

# test_06
# It should format html file
# with settings from .editorconfig

TMP_FILE="$TMPDIR/$(uuidgen)"
cat file > "$TMP_FILE"
vim -u vimrc -c "execute 'silent call HtmlBeautify()' | w | q | q" "$TMP_FILE"
[ "$(cat $TMP_FILE)" = "$(cat expected)" ]
