#!/bin/bash

TMP_FILE="$(tempfile)"

echo $(cat file) > $TMP_FILE

vim -u vimrc -c "execute 'silent call JsxBeautify()' | w | q | q" $TMP_FILE

RESULT=$(cat $TMP_FILE)

cat $TMP_FILE > /tmp/lol

[ "$RESULT" = "$(cat expected)" ]
