#!/bin/bash

# issue 29
# false values from editorconfig should be treated as boolean false not string 'false'
# https://github.com/maksimr/vim-jsbeautify/issues/29

TMP_FILE="$(tempfile)"

echo $(cat file) > $TMP_FILE

vim -u vimrc -c "execute 'silent call JsBeautify()' | w | q | q" $TMP_FILE

RESULT=$(cat $TMP_FILE)

[ "$RESULT" = "$(cat expected)" ]
