" vim -u vimrc
set nocompatible

set nowrap

let root = '~/.vim/bundle'
" Change HOME directory on test dir
let $HOME = fnamemodify(expand("<sfile>"), ":h")

filetype off
syntax on

runtime macros/matchit.vim
exec 'set rtp+=../../../'
